<?php

/**
 * @file
 * Page and form to import drupal path redirects
 */
use Drupal\Component\Utility\UrlHelper;
use Drupal\redirect\Entity\Redirect;
use Drupal\path_redirect_import\RedirectImport;

/**
 * Function that processes the file
 */
function path_redirect_import_read_file($file, $options = array()) {
  $options += array(
    'delimiter' => ',',
    'no_headers' => TRUE,
    'override' => FALSE,
    'status_code' => '301',
    'language' => LANGUAGE_NONE,
  );

  if (!$f = fopen($file, 'r')) {
    return array('success' => FALSE, 'message' => array(t('Unable to read the file')));
  }
  $line_no = 0;
  $messages = array();
  $operations = array();
  $redirect_options = redirect_status_code_options();

  while ($line = fgetcsv($f, 0, $options['delimiter'])) {
    $line_no++;
    if ($line_no == 1 && !$options['no_headers']) {
      drupal_set_message(t('Skipping the header row.'));
      continue;
    }

    if (!is_array($line)) {
      $messages[] = t('Line @line_no is invalid.', array('@line_no' => $line_no));
      continue;
    }

    if (empty($line[0]) || empty($line[1])) {
      $messages[] = t('Line @line_no contains invalid data.', array('@line_no' => $line_no));
      continue;
    }
    if (empty($line[2])) {
      $line[2] = $options['status_code'];
    }
    else {
      if (!isset($redirect_options[$line[2]])) {
        $messages[] = t('Line @line_no contains invalid status code', array('@line_no' => $line_no));
        continue;
      }
    }

    if (\Drupal::moduleHandler()->moduleExists('language')) {
      if (empty($line[3])) {
        $line[3] = $options['language'];
      }
      else {
        $redirect_import = \Drupal::service('path_redirect_import.redirect_import');
        if (!$redirect_import->isValidLanguage($line[3])) {
          $messages[] = t('Line @line_no contains invalid language code', array('@line_no' => $line_no));
          continue;
        }
      }
    }

    $operations[] = array(
      '_path_redirect_import_save_redirect_callback', array($line, $options)
    );

  }
  fclose($f);

  $batch = array(
    'title' => t('saving redirects'),
    'operations' => $operations,
    'finished' => '_path_redirect_import_batch_finished',
    'file' => drupal_get_path('module', 'path_redirect_import') . '/path_redirect_import.module',
  );

  batch_set($batch);

  return array('message' => $messages);
}

function _path_redirect_import_save_redirect_callback($line, $options, &$context) {
  return \Drupal::service('path_redirect_import.redirect_import')->saveRedirectCallback($line, $options, $context);
}

function _path_redirect_import_batch_finished($success, $results, $operations) {
  // The 'success' parameter means no fatal PHP errors were detected. All
  // other error management should be handled using 'results'.
  if ($success) {
    $message = \Drupal::translation()->formatPlural(count($results), 'One redirect processed.', '@count redirects processed.');
  }
  else {
    $message = t('Finished with an error.');
  }
  drupal_set_message($message);
}
